Update patch set 3
Patch Set 3:

paladox@gerrit-test:~/gerrit$ bazel build plugins/github-webhooks
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/paladox/gerrit/plugins/github-webhooks/BUILD:3:1: in deps attribute of java_library rule //plugins/github-webhooks:github-webhooks__plugin: deps not allowed without srcs; move to runtime_deps?. Since this rule was created by the macro 'gerrit_plugin', the error might have been caused by the macro implementation in /home/paladox/gerrit/tools/bzl/plugin.bzl:31:12.
ERROR: Analysis of target '//plugins/github-webhooks:github-webhooks' failed; build aborted.
INFO: Elapsed time: 0.652s

which is ok as buck would have failled because it's missing java files.

Patch-set: 3
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>